# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision_detection.proto
# Protobuf Python Version: 4.25-main
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16vision_detection.proto\"\xed\x01\n\x14Vision_DetectionBall\x12\r\n\x05vel_x\x18\x01 \x01(\x02\x12\r\n\x05vel_y\x18\x02 \x01(\x02\x12\x0c\n\x04\x61rea\x18\x03 \x01(\r\x12\t\n\x01x\x18\x04 \x02(\x02\x12\t\n\x01y\x18\x05 \x02(\x02\x12\x0e\n\x06height\x18\x06 \x01(\x02\x12\x12\n\nball_state\x18\x07 \x01(\r\x12\x12\n\nlast_touch\x18\x08 \x01(\r\x12\r\n\x05valid\x18\t \x02(\x08\x12\r\n\x05raw_x\x18\n \x02(\x02\x12\r\n\x05raw_y\x18\x0b \x02(\x02\x12\x16\n\x0e\x63hip_predict_x\x18\x0c \x01(\x02\x12\x16\n\x0e\x63hip_predict_y\x18\r \x01(\x02\"\xb6\x02\n\x15Vision_DetectionRobot\x12\r\n\x05valid\x18\x01 \x02(\x08\x12\x10\n\x08robot_id\x18\x02 \x01(\r\x12\t\n\x01x\x18\x03 \x02(\x02\x12\t\n\x01y\x18\x04 \x02(\x02\x12\x13\n\x0borientation\x18\x05 \x01(\x02\x12\r\n\x05vel_x\x18\x06 \x01(\x02\x12\r\n\x05vel_y\x18\x07 \x01(\x02\x12\x12\n\nrotate_vel\x18\x08 \x01(\x02\x12\x14\n\x0c\x61\x63\x63\x65lerate_x\x18\t \x01(\x02\x12\x14\n\x0c\x61\x63\x63\x65lerate_y\x18\n \x01(\x02\x12\r\n\x05raw_x\x18\x0b \x02(\x02\x12\r\n\x05raw_y\x18\x0c \x02(\x02\x12\x17\n\x0fraw_orientation\x18\r \x01(\x02\x12\x11\n\traw_vel_x\x18\x0e \x01(\x02\x12\x11\n\traw_vel_y\x18\x0f \x01(\x02\x12\x16\n\x0eraw_rotate_vel\x18\x10 \x01(\x02\"\x99\x01\n\x15Vision_DetectionFrame\x12$\n\x05\x62\x61lls\x18\x01 \x02(\x0b\x32\x15.Vision_DetectionBall\x12-\n\rrobots_yellow\x18\x02 \x03(\x0b\x32\x16.Vision_DetectionRobot\x12+\n\x0brobots_blue\x18\x03 \x03(\x0b\x32\x16.Vision_DetectionRobot')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VISION_DETECTIONBALL']._serialized_start=27
  _globals['_VISION_DETECTIONBALL']._serialized_end=264
  _globals['_VISION_DETECTIONROBOT']._serialized_start=267
  _globals['_VISION_DETECTIONROBOT']._serialized_end=577
  _globals['_VISION_DETECTIONFRAME']._serialized_start=580
  _globals['_VISION_DETECTIONFRAME']._serialized_end=733
# @@protoc_insertion_point(module_scope)
